apiVersion: v1
kind: Service
metadata:
  name: {{ include "opal.fullname" . }}-opal
  labels:
    {{- include "opal.labels" . | nindent 4 }}
    app.kubernetes.io/component: opal
spec:
  type: {{ .Values.opal.service.type }}
  ports:
    - port: {{ .Values.opal.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.opal.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.opal.service.sshPort }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "opal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: opal
