{{- if and .Values.query.enabled (and .Values.query.webAPI.auth.enabled (not .Values.query.webAPI.auth.existingSecret.name)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "query-webapi-secret"  }}
  labels:
    {{- include "recruit.labels" . | nindent 4 }}
    app.kubernetes.io/component: query
type: Opaque
data:
  webApiAuthPassword: {{ .Values.query.webAPI.auth.password | b64enc | quote }}
{{- end -}}
