{{- $secretName := printf "%s-django-session-secret" (include "cloudera-hue.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "cloudera-hue.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $djangoSecret := (get $secretData "django-session-secret") | default (randAlphaNum 64 | b64enc) }}
  django-session-secret: {{ $djangoSecret | quote }}
