apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudera-hue.fullname" . }}-config
  labels:
    {{- include "cloudera-hue.labels" . | nindent 4 }}
data:
  z-hue.ini: |
    {{ include "cloudera-hue.tplvalues.render" (dict "value" .Values.hueConfig "context" $) | nindent 4 }}
  {{- if .Values.extraHueConfig }}
  zz-hue.ini: |
    {{ include "cloudera-hue.tplvalues.render" (dict "value" .Values.extraHueConfig "context" $) | nindent 4 }}
  {{- end }}
