{{- range $name, $spec := .Values.processors }}
{{- with $spec }}
{{- if .metrics }}
{{- if .metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stream-processors.fullname" $ }}-{{ $name }}-metrics
  labels:
    {{- include "stream-processors.labels" $ | nindent 4 }}
    app.kubernetes.io/version: {{ include "stream-processors.version-label-value" . }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}-{{ $name }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}-{{ $name }}
  ports:
    - protocol: "TCP"
      port: {{ .metrics.port | default 8080 }}
      targetPort: "metrics"
      name: "metrics"
{{- end }}
{{- end }}
{{- end }}
{{- end }}
