{{- range $name, $spec := .Values.processors }}
{{- with $spec }}
{{- if .metrics }}
{{- if .metrics.enabled }}
{{- $serviceMonitor := .metrics.serviceMonitor | default dict }}
{{- with $serviceMonitor }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "stream-processors.fullname" $ }}-{{ $name }}
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{- end }}
  labels:
    {{- include "stream-processors.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
    {{- if .additionalLabels }}
    {{- toYaml .additionalLabels | nindent 4 }}
    {{- end }}
spec:
  {{ if .endpoints}}
  {{- with .endpoints }}
  endpoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else -}}
  endpoints:
    - port: "http-metrics"
      path: {{ .path | default "/metrics"}}
      {{- if .interval }}
      interval: {{ .interval }}
      {{- end }}
      {{- if .scrapeTimeout }}
      scrapeTimeout: {{ .scrapeTimeout }}
      {{- end }}
  {{- end }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- include "stream-processors.labels" $ | nindent 6 }}
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}-{{ $name }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
