{{- range $name, $spec := .Values.processors }}
{{- with $spec }}
{{- if or .container.ports (and .metrics .metrics.enabled) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stream-processors.fullname" $ }}-{{ $name }}-metrics
  labels:
    {{- include "stream-processors.labels" $ | nindent 4 }}
    app.kubernetes.io/version: {{ include "stream-processors.version-label-value" . }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}-{{ $name }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}-{{ $name }}
  ports:
    {{ if .container.ports }}
    {{- range $port := .container.ports }}
    - protocol: {{ $port.protocol | default "TCP" }}
      port: {{ $port.containerPort }}
      targetPort: {{ $port.name | default $port.containerPort }}
      {{- if $port.name }}
      name: {{ $port.name }}
      {{- end }}
    {{- end }}
    {{- else if and .metrics .metrics.enabled -}}
    - protocol: "TCP"
      port: {{ .metrics.port | default 8080 }}
      targetPort: {{ .metrics.port | default 8080 }}
      name: "http-metrics"
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
