apiVersion: v1
kind: Service
metadata:
  name: {{ include "blaze.fullname" . }}-hl
  labels:
    {{- include "blaze.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
   {{- if .Values.metrics.enabled }}
    - port: {{ .Values.service.metricsPort }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
    {{- end }}
  selector:
    {{- include "blaze.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
