apiVersion: v2
name: datashield
description: A Helm chart for deploying the Opal server and a DataShield rock cluster.
type: application
home: https://opaldoc.obiba.org/en/latest/index.html
keywords:
  - DataShield
  - opal
  - obiba
sources:
  - https://github.com/obiba/opal
  - https://github.com/datashield/docker-rock
  - https://github.com/obiba/docker-opal
maintainers:
  - name: miracum
dependencies:
  - name: postgresql
    version: 16.3.2
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 2.29.1
deprecated: false
kubeVersion: ">= 1.19.0"
version: 0.7.81
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/bitnami/postgresql
  # When using the list of objects option the valid supported kinds are
  # added, changed, deprecated, removed, fixed and security.
  artifacthub.io/changes: |-
    # When using the list of objects option the valid supported kinds are
    # added, changed, deprecated, removed, fixed and security.
    - kind: changed
      description: "Updated docker.io/library/busybox to sha256:2e72bee3c7dc01b1d74dfa33ed5a4b5214c181aa97d3d924939e4087a98e52e3"
