apiVersion: v2
name: datashield
description: A Helm chart for deploying the Opal server and a DataShield rock cluster.
type: application
home: https://opaldoc.obiba.org/en/latest/index.html
keywords:
  - DataShield
  - opal
  - obiba
sources:
  - https://github.com/obiba/opal
  - https://github.com/datashield/docker-rock
  - https://github.com/obiba/docker-opal
maintainers:
  - name: miracum
dependencies:
  - name: postgresql
    version: 15.5.14
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 2.20.3
deprecated: false
kubeVersion: ">= 1.19.0"
version: 0.6.0
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/bitnami/postgresql
  # When using the list of objects option the valid supported kinds are
  # added, changed, deprecated, removed, fixed and security.
  artifacthub.io/changes: |
    - kind: changed
      description: "Set default resource requests and limits for all containers using presets"
    - kind: changed
      description: "added service account settings"
