# -- override the release name
nameOverride: ""

# -- override the full release name
fullnameOverride: ""

opal:
  # -- number of replicas. Should be kept as 1 unless ReadWriteMany persistence is used
  replicaCount: 1

  # @ignored
  image:
    registry: docker.io
    repository: obiba/opal
    tag: 4.7@sha256:e6c3802296d9de1a29151cb528ff7ef83aeb16599dfb77bbc6df59a87382c2a4
    pullPolicy: IfNotPresent

  auth:
    administrator:
      # -- the password for the administrator user. If unset and no existing secret is specified, a random one is generated.
      password: ""
      existingSecret:
        # -- name of an existing secret that contains the administrator password.
        name: ""
        # -- key inside that existing secret that contains the administrator password
        key: "opal-administrator-password"

  ingress:
    # -- create an Ingress for the application
    enabled: false
    # -- ingressClassName to use
    className: ""
    # -- extra annotations to apply to the Ingress resource
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    # -- list of ingress hosts
    hosts:
      - host: opal.127.0.0.1.nip.io
        paths:
          - path: /
            pathType: ImplementationSpecific
            portName: https
    # -- TLS configuration
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  # -- configuration for the server persistence
  persistence:
    # -- enable data persistence using PVC
    enabled: true
    # -- name of an existing PVC to use
    existingClaim: ""
    # -- PVC Storage Class for data volume
    # If defined, storageClassName: <storageClass>
    # If set to "-", storageClassName: "", which disables dynamic provisioning
    # If undefined (the default) or set to null, no storageClassName spec is
    #   set, choosing the default provisioner.
    storageClass: ""
    # -- PVC Access Mode for data volume
    accessModes:
      - ReadWriteOnce
    # -- PVC Storage Request for volume
    size: 8Gi
    # -- annotations for the PVC
    annotations: {}
    # -- labels for the PVC
    labels: {}
    # -- selector to match an existing Persistent Volume (this value is evaluated as a template)
    # selector:
    #   matchLabels:
    #     app: my-app
    selector: {}

  database:
    data:
      # -- database hostname of an external database used to store data. Only used if `postgresql.enabled` is set to `false`.
      host: "data.host.example.com"
      # -- port used to connect to the postgres DB
      port: 5432
      # -- name of the database inside. If postgresql.enabled=true, then postgresql.postgresqlDatabase is used
      database: "opal_data"
      # -- username used to connect to the DB. Note that this name is currently used even if postgresql.enabled=true
      username: "opal_data_admin"
      # -- the database password. Only used if postgresql.enabled=false, otherwise the secret created by the postgresql chart is used
      password: "opal_data_password"
      existingSecret:
        # -- name of an existing secret containing the password to the DB.
        name: ""
        # -- name of the key in `database.data.existingSecret.name` to use as the password to the DB.
        key: "password"
    ids:
      # -- database hostname of an external database used to store ids. Only used if `postgresql.enabled` is set to `false`.
      host: "data.host.example.com"
      # -- port used to connect to the postgres DB
      port: 5432
      # -- name of the database inside. If postgresql.enabled=true, then postgresql.postgresqlDatabase is used
      database: "opal_ids"
      # -- username used to connect to the DB. Note that this name is currently used even if postgresql.enabled=true
      username: "opal_ids_password"
      # -- the database password. Only used if postgresql.enabled=false, otherwise the secret created by the postgresql chart is used
      password: "opal"
      existingSecret:
        # -- name of an existing secret containing the password to the DB.
        name: ""
        # -- name of the key in `database.data.existingSecret.name` to use as the password to the DB.
        key: "password"

  # -- extra environment variables to set on the opal api container
  extraEnv: []

  # -- image pull secrets used by the opal container
  imagePullSecrets: []

  # -- annotations to set on the opal pod
  podAnnotations: {}

  # -- the pod security context
  podSecurityContext:
    fsGroup: 101

  # @ignored
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    runAsUser: 101
    runAsGroup: 65534
    seccompProfile:
      type: RuntimeDefault

  service:
    # -- the type of service
    type: ClusterIP
    # -- the port for the main web interface
    port: 8080
    # -- the port for the TLS-secured interface
    httpsPort: 8443
    # -- the port for SSH access
    sshPort: 8022

  # -- resource limits and requests
  resources:
    {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # -- pod node selector
  nodeSelector: {}

  # -- pod tolerations
  tolerations: []

  # -- pod affinity
  affinity: {}

  # -- readiness probe
  # @ignored
  readinessProbe:
    httpGet:
      path: /ui/index.html
      port: http
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 20

  # -- liveness probe
  # @ignored
  livenessProbe:
    httpGet:
      path: /ui/index.html
      port: http
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 30

# @ignored
waitForDatabaseInitContainer:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 16.2.0-debian-12-r10@sha256:feff5aed093bcb118bd98b168a21a92bd4e82cfd35f0b6cd0032e2e63a4488ec
    pullPolicy: IfNotPresent

# -- container security context applied to init containers and the Helm test pods
# @ignored
restrictedContainerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  privileged: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  seccompProfile:
    type: RuntimeDefault

# @ignored
postgresql:
  enabled: true
  auth:
    database: opal

rock:
  # -- number of rock instances in the cluster
  replicaCount: 1

  # @ignored
  image:
    registry: docker.io
    repository: datashield/rock-base
    tag: "6.3@sha256:ebb5be25ccdaa59ff780b55bb12208c365ab03d7c0dae3412578c97d6268f3e3"
    pullPolicy: IfNotPresent

  # -- rock cluster name. Evaluated as a template
  clusterName: "default"

  auth:
    administrator:
      # -- the user name for the administrator user.
      name: "administrator"
      # -- the password for the administrator user. If unset and no existing secret is specified, a random one is generated.
      password: ""
      existingSecret:
        # -- name of an existing secret that contains the administrator password.
        name: ""
        # -- key inside that existing secret that contains the administrator password
        key: "rock-administrator-password"
    manager:
      # -- the user name for the manager user.
      name: "manager"
      # -- the password for the manager user. If unset and no existing secret is specified, a random one is generated.
      password: ""
      existingSecret:
        # -- name of an existing secret that contains the manager password.
        name: ""
        # -- key inside that existing secret that contains the manager password
        key: "rock-manager-password"
    user:
      # -- the user name for the user user.
      name: "user"
      # -- the password for the user. If unset and no existing secret is specified, a random one is generated.
      password: ""
      existingSecret:
        # -- name of an existing secret that contains the user password.
        name: ""
        # -- key inside that existing secret that contains the user password
        key: "rock-user-password"

  # -- resource limits and requests
  resources: {}

  # -- configuration for the server persistence
  persistence:
    # -- enable data persistence using PVC
    enabled: true
    # -- name of an existing PVC to use
    existingClaim: ""
    # -- PVC Storage Class for data volume
    # If defined, storageClassName: <storageClass>
    # If set to "-", storageClassName: "", which disables dynamic provisioning
    # If undefined (the default) or set to null, no storageClassName spec is
    #   set, choosing the default provisioner.
    storageClass: ""
    # -- PVC Access Mode for data volume
    accessModes:
      - ReadWriteOnce
    # -- PVC Storage Request for volume
    size: 8Gi
    # -- annotations for the PVC
    annotations: {}
    # -- labels for the PVC
    labels: {}
    # -- selector to match an existing Persistent Volume (this value is evaluated as a template)
    # selector:
    #   matchLabels:
    #     app: my-app
    selector: {}

  service:
    # -- the type of service
    type: ClusterIP
    # -- the port for the REST API
    port: 8085

  # @ignored
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    privileged: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    runAsUser: 105
    runAsGroup: 65534
    seccompProfile:
      type: RuntimeDefault

  # -- pod security context
  podSecurityContext:
    fsGroup: 105

  # -- pod node selector
  nodeSelector: {}

  # -- pod tolerations
  tolerations: []

  # -- pod affinity
  affinity: {}

  # -- readiness probe
  # @ignored
  readinessProbe:
    httpGet:
      path: /_check
      port: http
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 20

  # -- liveness probe
  # @ignored
  livenessProbe:
    httpGet:
      path: /_info
      port: http
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 30

# @ignored
curl:
  image:
    registry: docker.io
    repository: curlimages/curl
    tag: 8.7.1@sha256:25d29daeb9b14b89e2fa8cc17c70e4b188bca1466086907c2d9a4b56b59d8e21

tests:
  # -- configure the test pods resource requests and limits
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

logCollectorSidecar:
  # @ignored
  image:
    registry: docker.io
    repository: library/busybox
    tag: 1.36.1-uclibc@sha256:f9673c18abc855770e7de2f1bafd341a514facf10d5b1036c362c66ee1c1ccaf
  # -- configure the resources used by the log collector sidecar container used to tail the
  # filesystem-stored log files
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
