rock:
  replicaCount: 3

opal:
  ingress:
    enabled: true
    hosts:
      - host: opal.127.0.0.1.nip.io
        paths:
          - path: /
            pathType: ImplementationSpecific
            portName: https
