remote: origin
lint-conf: .github/ct/lintconf.yaml
chart-yaml-schema: .github/ct/chart-schema.yaml
validate-maintainers: false
validate-chart-schema: true
validate-yaml: true
check-version-increment: true
chart-dirs:
  - charts
upgrade: true
skip-missing-values: true
release-label: release
chart-repos:
  - codecentric=https://codecentric.github.io/helm-charts
  - hapifhir=https://hapifhir.github.io/hapi-fhir-jpaserver-starter
release-notes-file: CHANGELOG.md
target-branch: master
