chart-dirs:
  - charts
chart-repos:
  - codecentric=https://codecentric.github.io/helm-charts
  - hapifhir=https://hapifhir.github.io/hapi-fhir-jpaserver-starter
debug: true
remote: origin
helm-extra-args: --timeout 600s
