chart-dirs:
  - charts
chart-repos:
  - codecentric=https://codecentric.github.io/helm-charts
  - hapifhir=https://hapifhir.github.io/hapi-fhir-jpaserver-starter
  - trinodb=https://trinodb.github.io/charts
debug: true
remote: origin
helm-extra-args: --timeout 600s
target-branch: master
excluded-charts:
  - common
