{{- if (not .Values.postgresql.enabled) -}}
{{- if (not .Values.sinks.postgres.external.existingSecret) -}}
{{- if (.Values.sinks.postgres.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fhir-gateway.fullname" . }}-postgres-secret
  labels:
    {{- include "fhir-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: fhir-gateway
type: Opaque
data:
  postgresql-password: {{ .Values.sinks.postgres.external.password | b64enc | quote }}
{{- end -}}
{{- end -}}
{{- end -}}
