fhir-pseudonymizer:
  pseudonymizationService: "Vfps"
  vfps:
    enabled: true
    postgresql:
      enabled: true
      nameOverride: "vfps-postgres"
    resourcesPreset: "micro"

metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prom-stack
