fhir-pseudonymizer:
  pseudonymizationService: Vfps
  vfps:
    enabled: true
    postgresql:
      auth:
        postgresPassword: "vfps-postgres"
    appsettings: |
      {
        "Init": {
          "v1": {
            "Namespaces": [
              {
                "Name": "patient-identifiers",
                "Description": "Pseudonyms for patient identifiers",
                "PseudonymGenerationMethod": "SecureRandomBase64UrlEncoded",
                "PseudonymLength": 32,
                "PseudonymPrefix": "pid-"
              },
              {
                "Name": "visit-identifiers",
                "Description": "Pseudonyms for visit identifiers",
                "PseudonymGenerationMethod": "SecureRandomBase64UrlEncoded",
                "PseudonymLength": 32,
                "PseudonymPrefix": "vid-"
              }
            ]
          }
        }
      }

  anonymizationConfig: |
    fhirVersion: R4
    fhirPathRules:
      - path: nodesByType('HumanName')
        method: redact
      - path: nodesByType('Identifier').where(type.coding.system='http://terminology.hl7.org/CodeSystem/v2-0203' and type.coding.code='VN').value
        method: pseudonymize
        domain: visit-identifiers
      - path: nodesByType('Identifier').where(type.coding.system='http://terminology.hl7.org/CodeSystem/v2-0203' and type.coding.code='MR').value
        method: pseudonymize
        domain: patient-identifiers
    parameters:
      dateShiftKey: ""
      dateShiftScope: resource
      cryptoHashKey: "secret"
      encryptKey: ""
      enablePartialAgesForRedact: true
      enablePartialDatesForRedact: true
      enablePartialZipCodesForRedact: true
      restrictedZipCodeTabulationAreas: []
