fhir-pseudonymizer:
  pseudonymizationService: Vfps
  vfps:
    enabled: true
    postgresql:
      auth:
        postgresPassword: "postgres"
        database: "vfps"

  anonymizationConfig: |
    fhirVersion: R4
    fhirPathRules:
      - path: nodesByType('HumanName')
        method: redact
      - path: nodesByType('Identifier').where(type.coding.system='http://terminology.hl7.org/CodeSystem/v2-0203' and type.coding.code='VN').value
        method: pseudonymize
        domain: patient-identifiers
      - path: nodesByType('Identifier').where(type.coding.system='http://terminology.hl7.org/CodeSystem/v2-0203' and type.coding.code='MR').value
        method: pseudonymize
        domain: visit-identifiers
      - path: nodesByType('Identifier').where(type.coding.system='http://fhir.de/CodeSystem/identifier-type-de-basis' and type.coding.code='GKV' or type.coding.code='PKV')
        method: redact
    parameters:
      dateShiftKey: ""
      dateShiftScope: resource
      cryptoHashKey: "secret"
      encryptKey: ""
      enablePartialAgesForRedact: true
      enablePartialDatesForRedact: true
      enablePartialZipCodesForRedact: true
      restrictedZipCodeTabulationAreas: []
