{{- if and (not (index .Values "fhir-pseudonymizer" "enabled")) (not .Values.list.dePseudonymization.existingApiKeySecret.name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "recruit.list.fhirPseudonymizer.apiKey.secretName" . }}
  labels:
    {{- include "recruit.labels" . | nindent 4 }}
    app.kubernetes.io/component: list
type: Opaque
data:
  {{ include "recruit.list.fhirPseudonymizer.apiKey.secretKey" . }}: {{ .Values.list.dePseudonymization.apiKey | b64enc | quote }}
{{- end -}}
