{{- if .Values.list.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "recruit.fullname" . }}-list
  labels:
    {{- include "recruit.labels" . | nindent 4 }}
    app.kubernetes.io/component: list
spec:
  type: {{ .Values.list.service.type }}
  ports:
    - port: {{ .Values.list.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "recruit.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: list
{{- end }}
