{{- if and (.Values.auth.apiKey.enabled) (not .Values.auth.apiKey.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fhir-pseudonymizer.fhirPseudonymizerApiKeySecretName" . }}
  labels:
    {{- include "fhir-pseudonymizer.labels" . | nindent 4 }}
type: Opaque
data:
  APIKEY: {{ .Values.auth.apiKey.key | b64enc | quote }}
{{- end -}}
