apiVersion: v1
kind: Service
metadata:
  name: {{ include "fhir-pseudonymizer.fullname" . }}-fhir-pseudonymizer
  labels:
    {{- include "fhir-pseudonymizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: fhir-pseudonymizer
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fhir-pseudonymizer
    app.kubernetes.io/instance: {{ .Release.Name }}-fhir-pseudonymizer
