{{- if and (.Values.gpas.auth.basic.enabled) (not .Values.gpas.auth.basic.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fhir-pseudonymizer.gpasBasicAuthSecretName" . }}
  labels:
    {{- include "fhir-pseudonymizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: fhir-pseudonymizer
type: Opaque
data:
  GPAS__AUTH__BASIC__PASSWORD: {{ .Values.gpas.auth.basic.password | b64enc | quote }}
{{- end -}}
