apiVersion: v1
kind: Service
metadata:
  name: {{ include "fhir-pseudonymizer.fullname" . }}
  labels:
    {{- include "fhir-pseudonymizer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "fhir-pseudonymizer.matchLabels" . | nindent 4 }}
