apiVersion: v1
kind: Service
metadata:
  name: {{ include "datashield.fullname" . }}-opal
  labels:
    {{- include "datashield.labels" . | nindent 4 }}
    app.kubernetes.io/component: opal
spec:
  type: {{ .Values.opal.service.type }}
  ports:
    - port: {{ .Values.opal.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.opal.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "datashield.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: opal
