frontend:
  enabled: true
  envDict:
    AUTH_ISSUER: "https://keycloak.localhost/realms/blaze"
    AUTH_CLIENT_ID: "test"
    AUTH_CLIENT_SECRET: "1234-5678-9012"
    AUTH_SECRET: "12345"
    PROTOCOL_HEADER: "x-forwarded-proto"
    HOST_HEADER: "x-forwarded-host"
