apiVersion: v2
name: recruit
type: application
description: Helm chart for deploying the MIRACUM recruitment infrastructure on Kubernetes.
home: https://miracum.github.io/recruit
keywords:
  - miracum
  - fhir
  - clinical trials
  - patient recruitment
  - omop cdm
  - ctrss
maintainers:
  - name: chgl
sources:
  - https://github.com/miracum/charts/tree/master/charts/recruit
  - https://github.com/miracum/recruit
deprecated: false
kubeVersion: ">= 1.21.0"
icon: https://miracum.github.io/recruit/_img/miracum-recruit-k8s-logo.png
dependencies:
  - condition: fhirserver.enabled
    alias: fhirserver
    name: hapi-fhir-jpaserver
    repository: https://hapifhir.github.io/hapi-fhir-jpaserver-starter
    version: 0.10.1
  - condition: ohdsi.enabled
    name: ohdsi
    repository: https://chgl.github.io/charts
    version: 0.19.1
  - condition: mailhog.enabled
    name: mailhog
    repository: https://codecentric.github.io/helm-charts
    version: 5.2.0
  - condition: postgresql.enabled
    name: postgresql
    version: 11.9.8
    repository: https://charts.bitnami.com/bitnami
version: 9.2.3
appVersion: "9.x"
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: AGPL-3.0-or-later
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
    - url: https://artifacthub.io/packages/helm/bitnami/postgresql
    - url: https://artifacthub.io/packages/helm/chgl/fhir-server-exporter
    - url: https://artifacthub.io/packages/helm/jaegertracing/jaeger
  artifacthub.io/links: |
    - name: Deployment Instructions
      url: https://miracum.github.io/recruit/deployment/kubernetes/
  artifacthub.io/screenshots: |
    - title: Definition of eligibility criteria in the OHDSI ATLAS tool
      url: https://miracum.github.io/recruit/_img/atlas-first-cohort/atlas-test-cohort-definition.png
    - title: Screening list overview
      url: https://miracum.github.io/recruit/_img/atlas-first-cohort/list-overview-with-test-study.png
    - title: Screening recommendations for a test study
      url: https://miracum.github.io/recruit/_img/atlas-first-cohort/list-test-study.png
    - title: Email generated by the notify module
      url: https://miracum.github.io/recruit/_img/atlas-first-cohort/mailhog-opened.png
  artifacthub.io/changes: |
    # When using the list of objects option the valid supported kinds are
    # added, changed, deprecated, removed, fixed and security.
    - kind: changed
      description: updated ohdsi sub-chart to v0.19.1. This version allows enabling distributed tracing for the OHDSI WebAPI component.
    - kind: changed
      description: updated postgresql sub-chart to v11.9.8
    - kind: changed
      description: updated curlimages/curl to v7.85.0
