apiVersion: v2
name: recruit
type: application
description: Helm chart for deploying the MIRACUM recruitment infrastructure on Kubernetes.
home: https://miracum.github.io/recruit
keywords:
  - miracum
  - fhir
  - clinical trials
  - patient recruitment
  - omop cdm
  - ctrss
maintainers:
  - name: chgl
sources:
  - https://github.com/miracum/charts/tree/master/charts/recruit
  - https://github.com/miracum/recruit
deprecated: false
kubeVersion: ">= 1.21.0"
icon: https://miracum.github.io/recruit/_img/miracum-recruit-k8s-logo.png
dependencies:
  - condition: fhirserver.enabled
    alias: fhirserver
    name: hapi-fhir-jpaserver
    repository: https://hapifhir.github.io/hapi-fhir-jpaserver-starter
    version: 0.9.0
  - condition: ohdsi.enabled
    name: ohdsi
    repository: https://chgl.github.io/charts
    version: 0.17.18
  - condition: mailhog.enabled
    name: mailhog
    repository: https://codecentric.github.io/helm-charts
    version: 5.2.0
  - condition: postgresql.enabled
    name: postgresql
    version: 11.7.1
    repository: https://charts.bitnami.com/bitnami
version: 9.1.5
appVersion: "9.x"
annotations:
  artifacthub.io/license: AGPL-3.0-or-later
  artifacthub.io/links: |
    - name: Deployment Instructions
      url: https://miracum.github.io/recruit/deployment/kubernetes/
  artifacthub.io/screenshots: |
    - title: Definition of eligibility criteria in the OHDSI ATLAS tool
      url: https://miracum.github.io/recruit/_img/atlas-first-cohort/atlas-test-cohort-definition.png
    - title: Screening list overview
      url: https://miracum.github.io/recruit/_img/atlas-first-cohort/list-overview-with-test-study.png
    - title: Screening recommendations for a test study
      url: https://miracum.github.io/recruit/_img/atlas-first-cohort/list-test-study.png
    - title: Email generated by the notify module
      url: https://miracum.github.io/recruit/_img/atlas-first-cohort/mailhog-opened.png
  artifacthub.io/changes: |
    # When using the list of objects option the valid supported kinds are
    # added, changed, deprecated, removed, fixed and security.
    - kind: changed
      description: |
        dropped `tracing.enabled` setting in favor of module-specific configuration.
        See [README.md](/charts/recruit/README.md#distributed-tracing).
    - kind: changed
      description: update ghcr.io/miracum/recruit/query docker tag to v3.16.4
    - kind: changed
      description: update ghcr.io/miracum/recruit/notify docker tag to v3.2.5
    - kind: changed
      description: update ghcr.io/miracum/recruit/list docker tag to v2.15.6
    - kind: changed
      description: updated `waitForPostgresInitContainer` to 14.5.0-debian-11-r1
