{{- if and .Values.notify.enabled (not .Values.notify.mail.server.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "smtp"  }}
  labels:
    {{- include "recruit.labels" . | nindent 4 }}
    app.kubernetes.io/component: notify
type: Opaque
data:
  {{- if .Values.mailhog.enabled }}
  smtp-password: ""
  {{- else }}
  smtp-password: {{ .Values.notify.mail.server.password | b64enc | quote }}
  {{- end }}
{{- end }}
