{{- if and .Values.notify.enabled (not .Values.notify.ha.database.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "notify-ha-db"  }}
  labels:
    {{- include "recruit.labels" . | nindent 4 }}
    app.kubernetes.io/component: notify
type: Opaque
data:
  postgresql-password: {{ .Values.notify.ha.database.password | b64enc | quote }}
{{- end }}
