pseudonymizationService: Vfps

replicaCount: 3

vfps:
  enabled: true
  replicaCount: 2
  postgres:
    auth:
      postgresPassword: "postgres"
      database: "vfps"

auth:
  apiKey:
    enabled: true
    key: test

anonymizationConfig: |
  ---
  fhirVersion: R4
  fhirPathRules:
    - path: nodesByType('HumanName')
      method: redact
    - path: nodesByType('Identifier').where(type.coding.system='http://terminology.hl7.org/CodeSystem/v2-0203' and type.coding.code='VN').value
      method: pseudonymize
      namespace: test
    - path: nodesByType('Identifier').where(type.coding.system='http://terminology.hl7.org/CodeSystem/v2-0203' and type.coding.code='MR').value
      method: pseudonymize
      domain: test2
  parameters:
    dateShiftKey: ""
    dateShiftScope: resource
    cryptoHashKey: fhir-pseudonymizer
    # must be of a valid AES key length; here the key is padded to 192 bits
    encryptKey: fhir-pseudonymizer000000
    enablePartialAgesForRedact: true
    enablePartialDatesForRedact: true
    enablePartialZipCodesForRedact: true
    restrictedZipCodeTabulationAreas: []

ingress:
  enabled: true
  hosts:
    - host: fhir-pseudonymizer.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
          portName: http
