{{- if .Values.migrationsJob.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vfps.migrationsJob.serviceAccountName" . }}
  labels:
    {{- include "vfps.labels" . | nindent 4 }}
  {{- with .Values.migrationsJob.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
