{{- if .Values.rock.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "datashield.rock.serviceAccountName" . }}
  labels:
    {{- include "datashield.labels" . | nindent 4 }}
  {{- with .Values.rock.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
