{{- with  .Values.rock -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  {{ include "datashield.fullname" $ }}-rock
  labels:
    {{- include "datashield.labels" $ | nindent 4 }}
    app.kubernetes.io/component: rock
spec:
  replicas: {{ .replicaCount }}
  serviceName: {{ include "datashield.fullname" $ }}-rock
  selector:
    matchLabels:
      {{- include "datashield.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: rock
  template:
    metadata:
      labels:
        {{- include "datashield.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: rock
    spec:
      {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      initContainers:
        - name: first-run
          image: "{{ .image.registry }}/{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          command:
            - /bin/sh
            - -c
            - >
              mkdir -p /srv/conf &&
              cp -r /usr/share/rock/conf/* /srv/conf &&
              /opt/obiba/bin/first_run.sh
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: srv
              mountPath: /srv
            - name: data
              mountPath: /var/lib/rock/
      containers:
        - name: rock
          image: "{{ .image.registry }}/{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          command: [ "/usr/share/rock/bin/rock" ]
          ports:
            - name: http
              containerPort: 8085
              protocol: TCP
          env:
            - name: ROCK_CLUSTER
              value: "{{ include "datashield.fullname" $ }}"
            - name: ROCK_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: srv
              mountPath: /srv
            - name: data
              mountPath: /var/lib/rock/
          resources:
            {{- toYaml .resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: srv
          emptyDir: {}
  {{- if and .persistence.enabled .persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ tpl .persistence.existingClaim $ }}
  {{- else if not .persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
        {{- with .persistence.annotations  }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .persistence.labels  }}
        labels:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
        {{- range .persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .persistence.size | quote }}
        {{- if .persistence.selector }}
        selector: {{- include "datashield.tplvalues.render" (dict "value" .persistence.selector "context" $) | nindent 10 }}
        {{- end }}
        {{- include "datashield.storage.class" (dict "persistence" .persistence "global" $.Values.global) | nindent 8 }}
  {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
